name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
      - master
      - qodana
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with no coverage driver
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          extensions: bcmath, intl
        env:
          update: true
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: composer install

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3.3
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}